### ISSUE TITLE
Generate the front-page from individual Markdown pages 

### ISSUE THREAD

**Issue by dlecan** [unik-name/uns-delegates-website#3]
# General idea

From the following structure:

```
docs
   +- delegates
       +- <unikid1>
             +- README.md (front-matter and markdown)
             +- logo.png
```

generated to website landing page with:
- a section for each type of @unikname (only indiv. and org.)
- in each section, a UI box for each delegate in this type of @unikname

# TODOs
- [x] Write a Vuepress "plugin" to generate the landing page (plugin inner the current project)
- [x] Design and propose the 1st version of the delegate's README.md` (specific properties of Front-matter and Markdown suggested format)
- [x] Write a contribution rules document to explain to the delegates how to contribute their own information (in the README of the current project)
